platform :ios, '12.0'

target 'QGVAPDemo' do
  use_frameworks!

  pod 'QGVAPlayer', :path => '../..'
  pod 'Masonry'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
